name: Build & Release Electron App

on:
  push:
    tags:
      - 'v*.*.*' # فقط زمانی اجرا می‌شود که یک تگ جدید پوش شود

jobs:
  # جاب برای بیلد گرفتن فقط روی لینوکس
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build for Linux (.deb & .AppImage)
        # دستور مستقیم برای ساخت فرمت‌های مورد نظر
        run: pnpm electron-builder --linux deb AppImage

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux # نام آرتیفکت
          path: dist/*.{deb,AppImage} # فقط فایل‌های deb و AppImage را آپلود می‌کند

  # جاب دوم: ایجاد Release در گیت‌هاب
  release:
    needs: build-linux # این جاب به جاب بیلد لینوکس وابسته است
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-linux # آرتیفکت ساخته شده در جاب قبلی را دانلود می‌کند
          path: release-assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # تمام فایل‌های دانلود شده را به Release ضمیمه می‌کند
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}